# Generated by Django 6.1.1 on 2026-09-16 00:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountants', '0004_backfill_ledger_dates'),
        ('accounts', '0005_collection_mode_overrides'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UpstreamSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('remittance', 'Paid to upstream'), ('commission_payout', 'Commission received from upstream')], db_index=True, max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('period', models.DateField(db_index=True, help_text='The month being settled, stored as its first day.')),
                ('settled_on', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('reference', models.CharField(blank=True, help_text='Bank reference or statement number.', max_length=80)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-settled_on', '-id'],
            },
        ),
        migrations.AddField(
            model_name='billingsettings',
            name='collection_mode',
            field=models.CharField(choices=[('reseller', 'Reseller collects'), ('upstream', 'Client pays upstream directly')], default='reseller', help_text='The default settlement arrangement. Individual clients can override it.', max_length=20),
        ),
        migrations.AddField(
            model_name='billingsettings',
            name='upstream_name',
            field=models.CharField(blank=True, help_text="The upstream operator's name, shown on settlement screens.", max_length=120),
        ),
        migrations.AddField(
            model_name='invoice',
            name='collection_mode',
            field=models.CharField(choices=[('reseller', 'Reseller collects'), ('upstream', 'Client pays upstream directly')], db_index=True, default='reseller', help_text='Who collects this bill. Fixed when the invoice is raised.', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text="The reseller's share of this bill.", max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='invoice',
            name='upstream_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text="The upstream operator's share.", max_digits=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='collection_mode',
            field=models.CharField(choices=[('reseller', 'Reseller collects'), ('upstream', 'Client pays upstream directly')], db_index=True, default='reseller', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='What the reseller earns from this payment.', max_digits=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='upstream_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text="The upstream operator's share of this payment.", max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank', 'Bank transfer'), ('online', 'Online (upstream portal)'), ('other', 'Other')], default='cash', max_length=20),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['collection_mode', 'received_on'], name='accountants_collect_bca7d8_idx'),
        ),
        migrations.AddField(
            model_name='upstreamsettlement',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='upstreamsettlement',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='upstreamsettlement',
            index=models.Index(fields=['kind', 'period'], name='accountants_kind_a5fec0_idx'),
        ),
    ]
