# Generated by Django 4.0.4 on 2022-05-14 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0004_onu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('nid', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('onu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='warehouse.onu')),
            ],
        ),
    ]
