# Generated by Django 4.0.4 on 2022-05-15 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('speed', models.CharField(max_length=50)),
                ('ggc', models.CharField(max_length=50)),
                ('fna', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reseller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('nid', models.CharField(max_length=50)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100, verbose_name='phone')),
                ('nid', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=100, unique=True, verbose_name='IP/UserName')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('onu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.onu')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.package')),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.reseller')),
            ],
        ),
    ]
