# Generated by Django 4.0.4 on 2022-05-15 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_onu'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='ip',
            field=models.CharField(max_length=100, unique=True, verbose_name='IP/UserName'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='onu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.onu'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='phone'),
        ),
    ]
