# Generated by Django 4.0.4 on 2022-06-15 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_clients_reseller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='reseller',
        ),
        migrations.DeleteModel(
            name='Reseller',
        ),
    ]
