# Generated by Django 6.1.1 on 2026-09-16 00:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_backfill_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='collection_mode',
            field=models.CharField(blank=True, choices=[('reseller', 'Reseller collects'), ('upstream', 'Client pays upstream directly')], db_index=True, default='', help_text='Leave blank to follow the default in billing settings.', max_length=20),
        ),
        migrations.AddField(
            model_name='package',
            name='commission_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Commission for this plan. Leave blank to use the rate in billing settings.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='subscription',
            name='commission_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Commission agreed for this client. Blank falls back to the package, then settings.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
